---
name: Renovate

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

env:
  LOG_LEVEL: info
  RENOVATE_CONFIG_FILE: .github/renovate.json5

jobs:
  renovate:
    runs-on: ubuntu-22.04
    name: Run renovate
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app_id: ${{ secrets.RENOVATE_ID }}

      - name: running renovate
        uses: renovatebot/github-action@v39.0.0
        with:
          token: '${{ steps.get_token.outputs.token }}'
