---
name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Run Scala Steward
    steps:
      - name: running scala steward
        uses: scala-steward-org/scala-steward-action@v2.62.0
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_PRIVATE_KEY }}
